export type HolidayType = "public" | "religious" | "traditional";
export type LunarDay = {
  gregorianDate: string;
  dayOfWeek: string;
  buddhistEraYear: number;
  buddhistEraYearKhmer: string;
  khmerYear: number;
  khmerYearKhmer: string;
  khmerMonth: string;
  moonStatus: string;
  moonDay: number;
  moonDayKhmer: string;
  animalYear: string;
  sak: string;
  isLeapMonth: boolean;
  isSilDay: boolean;
  lunarDateText: string;
  gregorianDateText: string;
  gregorianDayText: string;
  gregorianMonthText: string;
  gregorianYearText: string;
  observanceText?: string;
  fullText: string;
  holidays?: Holiday[];
};
export type Holiday = {
  date: string;
  nameKm: string;
  nameEn: string;
  type: HolidayType;
};
export function toIso(d: Date | string | number): string;
export function parseDate(d: Date | string | number): Date;
export function lunarOf(d: Date | string | number): LunarDay;
export function dayInfo(d: Date | string | number): LunarDay;
export function holidaysOfYear(year: number): Holiday[];
export function holidaysOn(iso: string): Holiday[];
export function khmerNum(v: string | number): string;
export function animalPair(lunar: LunarDay): [string, string];
export function silOf(lunar: LunarDay): boolean;
export const ZODIAC: string[];
export const ZODIAC_EN: Record<string, string>;
export const SAK: string[];
export const SAK_EN: Record<string, string>;
export const MONTH_EN: Record<string, string>;
export const WEEKDAYS_KM: string[];
