/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DayRouteImport } from './routes/day'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as MonthsRouteImport } from './routes/months'
import { Route as MoreRouteImport } from './routes/more'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsClearRouteImport } from './routes/settings/clear'
import { Route as SettingsPrivacyandpermissionRouteImport } from './routes/settings/privacyandpermission'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsDatecalculatorRouteImport } from './routes/tools/datecalculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayRoute = DayRouteImport.update({
  id: '/day',
  path: '/day',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthsRoute = MonthsRouteImport.update({
  id: '/months',
  path: '/months',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsClearRoute = SettingsClearRouteImport.update({
  id: '/clear',
  path: '/clear',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyandpermissionRoute =
  SettingsPrivacyandpermissionRouteImport.update({
    id: '/privacyandpermission',
    path: '/privacyandpermission',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsDatecalculatorRoute = ToolsDatecalculatorRouteImport.update({
  id: '/datecalculator',
  path: '/datecalculator',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day': typeof DayRoute
  '/download': typeof DownloadRoute
  '/events': typeof EventsRoute
  '/get-started': typeof GetStartedRoute
  '/months': typeof MonthsRoute
  '/more': typeof MoreRoute
  '/settings': typeof SettingsRouteWithChildren
  '/today': typeof TodayRoute
  '/tools': typeof ToolsRouteWithChildren
  '/weather': typeof WeatherRoute
  '/settings/clear': typeof SettingsClearRoute
  '/settings/privacyandpermission': typeof SettingsPrivacyandpermissionRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/tools/datecalculator': typeof ToolsDatecalculatorRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day': typeof DayRoute
  '/download': typeof DownloadRoute
  '/events': typeof EventsRoute
  '/get-started': typeof GetStartedRoute
  '/months': typeof MonthsRoute
  '/more': typeof MoreRoute
  '/today': typeof TodayRoute
  '/weather': typeof WeatherRoute
  '/settings/clear': typeof SettingsClearRoute
  '/settings/privacyandpermission': typeof SettingsPrivacyandpermissionRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/tools/datecalculator': typeof ToolsDatecalculatorRoute
  '/settings': typeof SettingsIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/day': typeof DayRoute
  '/download': typeof DownloadRoute
  '/events': typeof EventsRoute
  '/get-started': typeof GetStartedRoute
  '/months': typeof MonthsRoute
  '/more': typeof MoreRoute
  '/settings': typeof SettingsRouteWithChildren
  '/today': typeof TodayRoute
  '/tools': typeof ToolsRouteWithChildren
  '/weather': typeof WeatherRoute
  '/settings/clear': typeof SettingsClearRoute
  '/settings/privacyandpermission': typeof SettingsPrivacyandpermissionRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/tools/datecalculator': typeof ToolsDatecalculatorRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/day'
    | '/download'
    | '/events'
    | '/get-started'
    | '/months'
    | '/more'
    | '/settings'
    | '/today'
    | '/tools'
    | '/weather'
    | '/settings/clear'
    | '/settings/privacyandpermission'
    | '/settings/theme'
    | '/tools/datecalculator'
    | '/settings/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/day'
    | '/download'
    | '/events'
    | '/get-started'
    | '/months'
    | '/more'
    | '/today'
    | '/weather'
    | '/settings/clear'
    | '/settings/privacyandpermission'
    | '/settings/theme'
    | '/tools/datecalculator'
    | '/settings'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/day'
    | '/download'
    | '/events'
    | '/get-started'
    | '/months'
    | '/more'
    | '/settings'
    | '/today'
    | '/tools'
    | '/weather'
    | '/settings/clear'
    | '/settings/privacyandpermission'
    | '/settings/theme'
    | '/tools/datecalculator'
    | '/settings/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DayRoute: typeof DayRoute
  DownloadRoute: typeof DownloadRoute
  EventsRoute: typeof EventsRoute
  GetStartedRoute: typeof GetStartedRoute
  MonthsRoute: typeof MonthsRoute
  MoreRoute: typeof MoreRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TodayRoute: typeof TodayRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day': {
      id: '/day'
      path: '/day'
      fullPath: '/day'
      preLoaderRoute: typeof DayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/months': {
      id: '/months'
      path: '/months'
      fullPath: '/months'
      preLoaderRoute: typeof MonthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/clear': {
      id: '/settings/clear'
      path: '/clear'
      fullPath: '/settings/clear'
      preLoaderRoute: typeof SettingsClearRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacyandpermission': {
      id: '/settings/privacyandpermission'
      path: '/privacyandpermission'
      fullPath: '/settings/privacyandpermission'
      preLoaderRoute: typeof SettingsPrivacyandpermissionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/datecalculator': {
      id: '/tools/datecalculator'
      path: '/datecalculator'
      fullPath: '/tools/datecalculator'
      preLoaderRoute: typeof ToolsDatecalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsClearRoute: typeof SettingsClearRoute
  SettingsPrivacyandpermissionRoute: typeof SettingsPrivacyandpermissionRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsClearRoute: SettingsClearRoute,
  SettingsPrivacyandpermissionRoute: SettingsPrivacyandpermissionRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ToolsRouteChildren {
  ToolsDatecalculatorRoute: typeof ToolsDatecalculatorRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsDatecalculatorRoute: ToolsDatecalculatorRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DayRoute: DayRoute,
  DownloadRoute: DownloadRoute,
  EventsRoute: EventsRoute,
  GetStartedRoute: GetStartedRoute,
  MonthsRoute: MonthsRoute,
  MoreRoute: MoreRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TodayRoute: TodayRoute,
  ToolsRoute: ToolsRouteWithChildren,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
